/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC1155RoundsUpgradeable__factory } from "./ERC1155RoundsUpgradeable__factory";
export { ERC721RoundsUpgradeable__factory } from "./ERC721RoundsUpgradeable__factory";
